IDIR =.
CC=g++
CFLAGS=-std=c++11 -I$(IDIR) -ltommath
EXECUTABLE=-o exe
HEADERS=tommath.h tommath_class.h tommath_superclass.h

all : ecc.cpp
	$(CC) ecc.cpp $(CFLAGS) $(EXECUTABLE) 


clean :
	rm -f *.o rm *.out *.con *.orig execute 